name: Generate production build for ios locally

# Controls when the action will run
on:
  # Triggers the workflow on repository_dispatch events but only for the build-new-version event
  repository_dispatch:
    types: [build-new-version]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: create Google Services File
        env:
          DATA: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          echo $DATA | base64 --decode > ${{ github.workspace }}/GoogleService-Info.plist
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn

      - name: 🚀 Build app
        env:
          GOOGLE_SERVICES_INFO_PLIST: ${{ github.workspace }}/GoogleService-Info.plist
        run: eas build --non-interactive --platform ios --local -e production --output ${{ github.workspace }}/ios-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: ${{ github.workspace }}/ios-release.ipa
