name: Generate build for ios on EAS

# Controls when the action will run
on:
  # Triggers the workflow on repository_dispatch events but only for the build-new-version event
  repository_dispatch:
    types: [build-new-version]

jobs:
  build-eas-ios:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn

      - name: 🚀 Build app
        run: eas build --non-interactive --platform ios
